<?php

namespace Trexima\EuropeanCvBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyAccessor;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;

/**
 * Input for Dropzonejs AJAX uploads
 */
class JQueryFileUploadType extends AbstractType
{
    private readonly PropertyAccessor $accessor;

    public function __construct(
        private readonly string $uploadUrl,
        private readonly RouterInterface $router
    )
    {
        $this->accessor = PropertyAccess::createPropertyAccessor();
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options);

        $parentData = $form->getParent()->getData();
        $filename = null;
        if (null !== $parentData) {
            $filename = $this->accessor->getValue($parentData, $view->vars['name']);
        }

        $view->vars['upload_url'] = $this->router->generate($options['upload_route'], [], UrlGeneratorInterface::ABSOLUTE_URL);
        $view->vars['base_upload_url'] = rtrim($this->uploadUrl, '\\/').'/images/';
        $view->vars['filename'] = $filename;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults([
            // hidden fields cannot have a required attribute
            'required' => false,
            // Pass errors to the parent
            'error_bubbling' => true,
            'compound' => false,
        ]);

        $resolver->setRequired([
            'upload_route'
        ]);
    }
}